version: '3.7'

volumes:
 vault_postgres_policy: {}
 vault_seal_keys: {}
 consul_encrypt_key: {}

secrets:
  postgres_password:
    file: ./POSTGRES_PASSWORD

x-postgres-config: &postgres-env
  POSTGRES_HOST: postgres
  POSTGRES_DB: ${PG_DATABASE:-qwerty}
  POSTGRES_USER: ${PG_USER:-123abc}
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

networks:
  vault:
    external: false
  consul:
    external: false
  postgres:
    external: false

services:
  consul-setup:
    build:
      context: ./consul-setup
    volumes:
      - consul_encrypt_key:/consul
    restart: on-failure
  
  consul-bootstrap:
    image: consul:${CONSUL_VERSION:-1.7}
    ports:
      - 8500:8500
    volumes:
      - consul_encrypt_key:/consul
    networks:
      - consul
      - vault
    command: agent -config-file /consul/bootstrap.json
    depends_on:
      - consul-setup
    restart: on-failure

  consul-node1: &consul-setup
    image: consul:${CONSUL_VERSION:-1.7}
    command: agent -config-file /consul/nodes.json
    networks:
      - consul
    volumes:
      - consul_encrypt_key:/consul
    depends_on:
      - consul-bootstrap
      - consul-setup
    restart: on-failure

  consul-node2:
    <<: *consul-setup
    depends_on:
      - consul-node1

  vault:
    image: vault:${VAULT_VERSION:-1.3.5}
    command: vault server -config=/vault/config
    environment: &vault-env
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_LOCAL_CONFIG: >-
        {
            "ui": true,
            "backend": {
                "consul": {
                    "address": "consul-bootstrap:8500",
                    "path": "vault",
                    "scheme": "http"
                }
            },
            "default_lease_ttl": "168h",
            "listener": {
                "tcp": {
                    "address": "0.0.0.0:8200",
                    "tls_disable": "1"
                }
            },
            "max_lease_ttl": "720h"
        }
    cap_add:
      - IPC_LOCK
    networks:
      - vault
      - postgres
    depends_on:
      - consul-bootstrap
      - consul-node1
      - consul-node2
    restart: on-failure

  postgres:
    image: postgres:${POSTGRES_VERSION:-9.5}
    environment:
      <<: *postgres-env
    secrets:
      - postgres_password
    restart: on-failure
    networks:
      - postgres
    restart: on-failure

  vault-setup:
    build:
      context: ./vault-setup
      args:
        VAULT_VERSION: ${VAULT_VERSION:-1.3.5}
    volumes:
      - vault_postgres_policy:/consul/db_policy
      - vault_seal_keys:/keys
    environment:
      <<: *postgres-env
      <<: *vault-env
    secrets:
      - postgres_password
    cap_add:
      - IPC_LOCK
    networks:
      - vault
      - postgres
    depends_on:
      - consul-bootstrap
      - consul-node1
      - consul-node2
      - vault
      - postgres
    restart: on-failure

  kong:
    build:
      context: ./kong
    volumes:
      - vault_postgres_policy:/consul/db_policy
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_DATABASE: ${PG_DATABASE:-qwerty}
    networks:
      - consul
      - vault
      - postgres
    depends_on:
      - consul-bootstrap
      - consul-node1
      - consul-node2
      - vault
      - postgres
    restart: on-failure
